### ISSUE TITLE
Various Css changes

### ISSUE THREAD

**Issue by Emik234** [billyleroy/prj-rev-bwfs-dasmoto#2]
https://github.com/billyleroy/prj-rev-bwfs-dasmoto/blob/bcc6270de7a0e671704a56fc2774f37aa4aeb41c/dasmotos/resources/css/style.css#L1-L14

1. Because the background colors are specific and unique to each h2, I recommend using IDs instead of classes. 👍 

2. Since  the font-family is repeated so many times, I recommend using * or body to select the entire content and apply the font-family once.

3. The h1 and h2 are already bolded by default, we don't need to specify this.

**Comment by billyleroy** [comment]
Fixed
